#!/usr/bin/env bash
#
# Use the `standard` virtual environment to execute a Python command
#

# find source file directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

# activate the venv
VENVDIR="$WORKON_HOME/standard"
source "$VENVDIR/bin/activate" || exit 1

# Run py file
PYFILE="$SOURCE".py
python "$PYFILE" "$@"
