#!/usr/bin/env bash

# Cd into source file directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
cd -P "$( dirname "$SOURCE" )"

# Run py file
PYFILE="$(basename $SOURCE)".py
pipenv run python "$PYFILE" "$@"
